### ISSUE TITLE
Lifespan + Production Upgrade combo?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/gendustry#109]
Maybe I'm missunderstanding it, but if I use lifespan and production combo, do I get more stuff, in shorter amount of time?

Or is the lifespan upgrade thought to be for mutations?

**Comment by bdew** [comment]
Short version: Lifespan doesn't affect production in any way. It can be used to get more drones and/or to get faster mutations.

Basically the bees work in ticks, one "bee tick" happens about every 25 seconds. This is controlled by forestry and applies to any all apiaries/alvearies/etc from all mods.

Every tick the queen has a chance to generate products (speed allele and production upgrades affect that) and looses some health (lifespan alleles and upgrades affect that). Once health reaches 0 it dies and produces offspring.

Also questions like that are more appropriate for the forums, rather than an issue tracker :P

**Comment by Unrepentant-Atheist** [comment]
Yea, okay. Thanks. But that would be an idea for an upgrade don't you think? To only work in combination with production upgrade. Shorter amount of time, produce more stuff.Consume way more energy.

**Comment by bdew** [comment]
I wouldn't really give you more stuff in shorter time. Once you get to 100% production chance per bee tick, you can't get more than that. Shortening the lifespan would mean the bee dies faster but produces the same amount of stuff per unit of time.

**Comment by Unrepentant-Atheist** [comment]
Hmmm...right, might circumvent that with an industrial centrifuge with upgrades that are really expensive in terms of RF but output like double or something like that.
