### ISSUE TITLE
Crash on Server Start up

### ISSUE THREAD

**Issue by DoughnutDev** [bdew-minecraft/gendustry#114]
http://pastebin.com/7iVuGCLi

**Comment by bdew** [comment]
That crash makes no sense to me, can you upload the full log?

Also try re-downloading bdlib and gendustry. might be a corrupt download.

**Comment by DoughnutDev** [comment]
https://www.dropbox.com/s/paaoraz6gg6039p/fml-server-latest.log?dl=0

**Comment by bdew** [comment]
> Caused by: java.lang.NoClassDefFoundError: scala/util/parsing/combinator/JavaTokenParsers

Your install is borked. This class should be in the libraries installed by forge.

IF you installed using some non-standard method (e.g. some kind of server control panel) - report it to whomever is responsible for it. Otherwise try reinstalling / reuploading the files to the server, maybe something got messed up along the way.
