### ISSUE TITLE
Gene Storage Block

### ISSUE THREAD

**Issue by rye1994** [bdew-minecraft/gendustry#130]
I'm just starting to get into using the Isolater block to collect a serum for each of the species. Which is obviously a lot with Extra Bees and Magic Bees, plus the ones you add.

It would be nice if there was a block that you could throw all the serums in that would allow them to stack, and you can search through by name, and by gene type.

I know that sounds quite doable using AE2 but it could possibly have other features if anyone's able to think of them.

Thanks
Ryan

**Comment by bdew** [comment]
If you really mean isolator and serums  - this should be a feature request for [binnie's mods](https://bitbucket.org/binnie567/binnie-mods/issues) (since its' from that mod)

I do have some kind of storage planned for samples (which are similar to serums in use), but it's pretty down on my todo list.

**Comment by rye1994** [comment]
Apologies, I did mean your samples.

Thanks for replying.
Ryan
