### ISSUE TITLE
Not sure what is causing this

### ISSUE THREAD

**Issue by CollectorMaster** [bdew-minecraft/gendustry#147]
It's been working fine ever since I added the mods and then today it just did this and I can't load in. I have the forge thing so it has the screen with the bars. It loads fine until phase 3, 5/7 on the first bar, then headcrums 74/152. it then stays like this and doesn't load. here's the log. please fix cause I wanna play meh game. http://paste.ee/p/b7Bnt

**Comment by CollectorMaster** [comment]
I got rid of binnies and updated the mods and its still happening http://paste.ee/p/9YAD2

**Comment by bdew** [comment]
The part that should be running after that is registering the creative tabs. I don't really see any way for it to freeze the client.

If you want to investigate it more - download [VisualVM](https://visualvm.java.net/download.html), wait for the client to reach that stuck state, then find the process and take a thread dump.

![screenshot 94](https://cloud.githubusercontent.com/assets/96327/11582948/f8312dca-9a5c-11e5-9c01-e14344982ea0.png)

This will hopefully show what's exactly going on when it's stuck.

**Comment by Quarris** [comment]
I have a very similar if not exactly the same issue. It doesn't get stuck however whenever it gets to the 'Block Drops' phase during loading Gendustry Blocks take A LOT longer to the point where it feels like its not worth it anymore 
![image](https://cloud.githubusercontent.com/assets/6171764/21965921/342632a8-db61-11e6-8642-22551d35aa83.png)
This is one of them. After that is over everything loads in smoothly again.
------------------------------------------------------------------------------------
After writing this I was in processes of launching Minecraft. Im not going to remove what I just wrote.
I let the slow process of loading the Gendustry Block Drops to go through and the pack loaded. I then re-launched the pack and that problem was gone, it loaded smoothly right away.
Im not sure what is up but it just seems to be loading up really slow the first time the mod is loaded.

**Comment by bdew** [comment]
@Quarris likely not related to the original report here.

Are you running the latest gendustry/bdlib? There was a fix for some problems with BlockDrops mod in bdlib-1.12.2.19-mc1.10.2

**Comment by Quarris** [comment]
So I'm not sure what it was. But I loaded up my pack once and after that it was smooth loading all the other times. So I guess my problem is kinda fixed but I'm still a little confused. Thanks for the help anyways bdew!

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
