### ISSUE TITLE
Apple oak produces incorrect carbonization gene

### ISSUE THREAD

**Issue by chantrykomori** [bdew-minecraft/gendustry#181]
Vanilla apple oaks consistently produce Carbonization 4 gene samples when put into a gene sampler. According to the Alyzer, it should produce Carbonization 5. Is this a Gendustry bug, or a Forestry bug?

**Comment by bdew** [comment]
Weird. I'll look into it.

**Comment by bdew** [comment]
It seems that carbonization and combustibility alleles are being removed from forestry, there are still in the code but aren't actually used. 

The actual carbonization and combustibility are now tied directly to the species of the tree - that's what you see in the analyzer.

Due to how the the sampler works you will still get samples for those alleles until forestry actually takes them out... but they are useless at the moment.
