### ISSUE TITLE
Client crashes when joining server

### ISSUE THREAD

**Issue by TheMrCaveman** [bdew-minecraft/gendustry#190]
Minecraft 1.10,2
Forge 12.18.2.2099
Gendustry 1.6.4.23 (MC 1.10.2)

Modpack Hermitpack FTB

Crash report: http://pastebin.com/GJ1ScbA1

**Comment by bdew** [comment]
Does this happen consistently or just a once-off thing?

ConcurrentModificationException are a bitch to debug because java doesn't report what the other thing doing the modification was...

**Comment by TheMrCaveman** [comment]
will test again tommorow  and let you know!

**Comment by TheMrCaveman** [comment]
Still the same issue

Server latest fml log:
http://pastebin.com/uAeACVhn

Client crash report:
http://pastebin.com/GJ1ScbA1

Client screen record:
https://youtu.be/V44DatFYC5c

**Comment by bdew** [comment]
Try updating bdlib to this build: https://minecraft.curseforge.com/projects/bdlib/files/2339442

I can't reproduce the issue here, but from looking at the code i have a suspicion this is actually a problem with vanilla code. I've tried adding a workaround that might or might not help, please test :)

**Comment by TheMrCaveman** [comment]
updated and now able to login normally!!
