### ISSUE TITLE
[1.10.2] WAILA sync issue on industrial apiaries info.

### ISSUE THREAD

**Issue by MrNinja93** [bdew-minecraft/gendustry#193]
Incredibly minor but I just noticed that the info for rf/t etc on the WAILA shift extended info on industrial apiaries resets itself to 20rf/t on leaving the area (client chunk unload) regardless of how much power is being used. Opening the GUI for the apiary re-syncs correct info. 

Gendustry version 1.6.4.21

![2016-10-21_23 44 15](https://cloud.githubusercontent.com/assets/21979276/19614012/ca413aa6-97e8-11e6-9a46-3d6918a3740e.png)
![2016-10-21_23 44 47](https://cloud.githubusercontent.com/assets/21979276/19614014/ca4b2de0-97e8-11e6-9882-7bee6b5556a4.png)

![2016-10-22_00 56 29](https://cloud.githubusercontent.com/assets/21979276/19615069/b9ec0726-97f2-11e6-9bb1-a81c4cb05fa9.png)
![2016-10-22_00 56 19](https://cloud.githubusercontent.com/assets/21979276/19615070/b9eda2d4-97f2-11e6-89eb-a5e66c7ae429.png)

**Comment by bdew** [comment]
I'm not sure what's going on with WAILA at the moment since the mod wasn't updated past 1.9.4 and ProfMobius seems to have disappeared since he was hired by mojang. There seems to be something borked with the client-server sync, either in WAILA itself or in how i use it.

I'll see if i can fix this for now, but i'm planning to switch to TheOneProbe at some point since it's the active alternative for 1.10+

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
