### ISSUE TITLE
Custom bee questions concerning "if HaveForestryModule Bees"

### ISSUE THREAD

**Issue by Lyl4c** [bdew-minecraft/gendustry#200]
Are there other if statements like this? 
Is there a list of modules or is this the only one? 
How can I control what bees to load for which mods that are present? (other than forestry or gendustry)

**Comment by bdew** [comment]
For HaveForestryModule see here - https://bdew.net/gendustry/configuration/haveforestrymodule-conditional/

See here for other conditional checks:  https://bdew.net/bacon/conditions/

You can use HaveMod to check for other mods. HaveOD can also be useful, but it won't always work since ore dictionary entries might not be registered by the time bees need to be evaluated.
