### ISSUE TITLE
[1.12.2] Unable to remove recipes with CraftTweaker

### ISSUE THREAD

**Issue by NielsPilgaard** [bdew-minecraft/gendustry#233]
Hey!

As the title says, I'm unable to remove recipes with CraftTweaker, most likely due to recipes being loaded in postInit. Would you mind moving it?

This is the same issue as https://github.com/bdew/ae2stuff/issues/156

**Comment by bdew** [comment]
Sorry unlike AE2Stuff there's actual reasons for stuff to happen in postInit. Since the same system that registers recipes from my configs also handles other stuff (like custom bees from user-provided configs and such), which might depend on other mods getting their stuff registered etc.

I am planning to switch the vanilla recipe to the new json system at some point, but until then you'll have to either use my config system or bug CT people to make it work with postInit.

In general it shouldn't be harder than dropping a config file into gendustry config folder with something like

```
clearRecipes: I:gendustry:IndustrialApiary
```

You can probably keep your custom recipes in CT and just use my system for recipe removal. You can read up more on it here - https://bdew.net/bacon/recipe-removal/

**Comment by NielsPilgaard** [comment]
Ah, fair enough. I'll use your config system, thanks!

**Comment by NielsPilgaard** [comment]
Another quick thing - I suspect there's an obvious reason this doesn't work, could you point it out? ^^'

clearRecipe: I:gendustry:genetics_processor
clearRecipe: I:gendustry:env_processor
clearRecipe: I:gendustry:mutagen_tank
clearRecipe: I:gendustry:upgrade_frame
clearRecipe: I:gendustry:power_module

It's in a file called recipeRemovals.cfg in the gendustry folder.

**Comment by bdew** [comment]
This looks about right... did you get it working?

**Comment by NielsPilgaard** [comment]
I did not, I did however get a weird crash with the above config, I was hoping it was because of wrong syntax.

https://gist.github.com/NillerMedDild/4155cdb33ac26e78c62f64eaa5309ea4

**Comment by bdew** [comment]
I'll look into it

**Comment by bdew** [comment]
derp! It should be clearRecipe**s** (plural)

clearRecipes: I:gendustry:genetics_processor
clearRecipes: I:gendustry:env_processor
clearRecipes: I:gendustry:mutagen_tank
clearRecipes: I:gendustry:upgrade_frame
clearRecipes: I:gendustry:power_module

**Comment by NielsPilgaard** [comment]
Woops :P The example you linked says clearRecipe in the example, but clearRecipes at the top.
Thanks for the help!

**Comment by bdew** [comment]
Fixed the example.

**Comment by NielsPilgaard** [comment]
Not sure if you get notifications on new posts in closed issues, but this issue has re-emerged. I'm using the same script as always:
 
`clearRecipes: I:gendustry:genetics_processor`
`clearRecipes: I:gendustry:env_processor`
`clearRecipes: I:gendustry:mutagen_tank`
`clearRecipes: I:gendustry:upgrade_frame`
`clearRecipes: I:gendustry:power_module`

However it no longer removes recipes.

**Comment by hron84** [comment]
@bdew Would you consider if you make recipe registration at least configurable? I mean we could disable recipe registration at all with a single command?

**Comment by PhantomPXL** [comment]
Im having a bit of a issue when trying to remove recipes from gendustry ive created the cfg file and added some items to be removed but when i add the id for the apiary upgrades it crashes and says this for the error: **_Description: Gendustry config loading failed in file C:\Users\Phantom_PXL\Twitch\Minecraft\Instances\M.A.D. - Mutually Assured Destruction (1)\config\gendustry\recipeRemovals.cfg: Config parsing failed at 10.33: string matching regex `\z' expected but `.' found_**

I think its befause the item id is gendustry:apiary.upgrade and it uses a period instead of a underscore like most items.

**Comment by hron84** [comment]
@bdew hello, the documentation site is broken, could you please give an example how to remove recipe for items with metadata?

**Comment by xANoyU** [comment]
> Not sure if you get notifications on new posts in closed issues, but this issue has re-emerged. I'm using the same script as always:
> 
> `clearRecipes: I:gendustry:genetics_processor` `clearRecipes: I:gendustry:env_processor` `clearRecipes: I:gendustry:mutagen_tank` `clearRecipes: I:gendustry:upgrade_frame` `clearRecipes: I:gendustry:power_module`
> 
> However it no longer removes recipes.

how to fix it?
