### ISSUE TITLE
[Suggestion] Protein Liquifier Compatibility

### ISSUE THREAD

**Issue by Xiaminou** [bdew-minecraft/gendustry#241]
Add compatibility to the Protein Liquifier for the popular food mods such as Pam's Harvestcraft.

Side note: I'm pretty sure it's liquefier and not liquifier

**Comment by bdew** [comment]
I'm busy with other more important stuff at the moment but if you want to contribute configs that add support for various mods i'll be more than happy to add them. See here for example - https://github.com/bdew/gendustry/blob/mc1.12/resources/assets/gendustry/config/recipes.cfg#L208

Also both are valid forms - https://en.wiktionary.org/wiki/liquifier

To me LIQUIfier makes more sense since it makes things LIQUId 😛
