### ISSUE TITLE
Gendustry bred leaves crashing game when attempting to remove from TE cache

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [bdew-minecraft/gendustry#94]
I couldn't be sure if gendustry is to blame. The trees, and the leaves were planted, harvested and fertilized with MFR, sent  to cache with pipes and upon left click, a crash is caused. Would you like to see the crash log? Should I just copy and paste it here?

**Comment by bdew** [comment]
Put it on gist or pastebin and link here, I'll take a look. 

Does it work without crashing without gendustry?

**Comment by GotchaGimmeThanks** [comment]
http://pastebin.com/rsk8tQDP

When I removed gendustry from my mod folder the game still crashed, giving what at first glance looks like the same report (this is the previous one).

There is still, upon loading, in my inventory bar a stack of 64 pictureless items. The cache when I clicked it was pictureless, and should have been filled with these cross bred leaves of mine. Interesting thing about these leaves: I'm never able to stack them in my inventory, and yes, the cache thing caused a lot of trouble.

I can't load back in, the game seems to be identifying these leaves as having the ID "325". I made a back up, then deleted every ID 325 using NBT, that did not help.

**Comment by bdew** [comment]
It looks to me that MFR is somehow corrupting forestry leafs when harvesting them. 

In your inventory they will show up without an icon and the tooltip will say something like "Unnamed 325" - this is because forestry doesn't know what tree they came from and can't give a name or texture.

The crash happens when they end up as your active item and Minecraft tries to show the name.

If you shear them manually they should work correctly with the cache and everything.

I have reproduced all that without gendustry so i'm pretty sure that it has nothing to do with it.

**Comment by GotchaGimmeThanks** [comment]
finally got rid of the offending plum leaves, which were a stack of 64 in my inventory (id 535) used mcedit2 to replace them with stone. In your non gendustry testing were the leaves unwilling to form stacks? Because that is still the case, except when they've been shoved into a cache and I try to pull them out in stack form....then they get angry and crash things.

**Comment by bdew** [comment]
I didn't notice problems with stacking. The crash should happen regardless of that if any oh them ends up in your active hotbar slot (in your hand)
